# Generated by Django 4.1.7 on 2023-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.CharField(max_length=100)),
                ("enfoque", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("repeticiones", models.CharField(max_length=100)),
                ("cadencia", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("dias", models.ManyToManyField(to="rutinas.dia")),
            ],
        ),
        migrations.AddField(
            model_name="dia",
            name="ejercicios",
            field=models.ManyToManyField(to="rutinas.ejercicio"),
        ),
    ]
