# Generated by Django 4.1.7 on 2023-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rutinas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dia",
            name="ejercicios",
            field=models.ManyToManyField(
                related_name="ejercicios", to="rutinas.ejercicio"
            ),
        ),
        migrations.AlterField(
            model_name="rutina",
            name="dias",
            field=models.ManyToManyField(related_name="dias", to="rutinas.dia"),
        ),
    ]
