# Generated by Django 4.1.7 on 2023-03-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rutinas", "0002_alter_dia_ejercicios_alter_rutina_dias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("focus", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="rutinas.day",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.IntegerField()),
                ("repetitions", models.IntegerField()),
                ("cadence", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="rutinas.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="rutina",
            name="dias",
        ),
        migrations.DeleteModel(
            name="Dia",
        ),
        migrations.DeleteModel(
            name="Ejercicio",
        ),
        migrations.DeleteModel(
            name="Rutina",
        ),
        migrations.AddField(
            model_name="day",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="rutinas.routine",
            ),
        ),
    ]
