# Generated by Django 4.1.7 on 2023-03-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rutinas", "0004_dia_ejercicio_rutina_remove_exercise_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutina",
            name="dias",
        ),
        migrations.AddField(
            model_name="dia",
            name="rutina",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dias",
                to="rutinas.rutina",
            ),
        ),
    ]
