# Generated by Django 4.1.7 on 2023-03-28 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rutinas", "0006_remove_dia_ejercicios_ejercicio_dia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ejercicio",
            old_name="nombre",
            new_name="ejercicio",
        ),
    ]
