# Generated by Django 4.1.7 on 2023-03-28 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rutinas", "0007_rename_nombre_ejercicio_ejercicio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ejercicio",
            old_name="ejercicio",
            new_name="nombre",
        ),
    ]
